name: Monitor Website Layout

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour (adjust as needed)
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium pillow pixelmatch

      - name: Run Website Layout Check
        run: python monitor_layout_changes.py

      - name: Upload Screenshots as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ./screenshots
