name: Monitor Website Layout Changes

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch: # Triggered manually

jobs:
  monitor_websites:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.p'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Playwright
      - name: Install Playwright browsers
        run: |
          python -m playwright install  # Installs the necessary browsers for Playwright

      # Run the layout monitor script
      - name: Run monitor_layout_changes.py
        run: python monitor_layout_changes.py

      # Read the changed URLs from the file
      - name: Read changed URLs
        id: get-changed-urls
        run: |
          if [ -f changed_urls.txt ]; then
            changed_urls=$(cat changed_urls.txt)
            echo "::set-output name=changed_urls::$changed_urls"
          else
            echo "::set-output name=changed_urls::No changes detected."
          fi

      # Send email alert (if there's a change)
      - name: Send email alert
        uses: dawidd6/action-send-mail@v3
        with:
          smtp-server: ${{ secrets.SMTP_HOST }}
          smtp-port: ${{ secrets.SMTP_PORT }}
          smtp-username: ${{ secrets.SMTP_USERNAME }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.SENDER_EMAIL }}
          to: ${{ secrets.RECIPIENT_EMAIL }}
          subject: GitHub Monitor - Website Change Alert
          body: |
            The following websites have been detected with layout changes:
            ${{ steps.get-changed-urls.outputs.changed_urls }}
